version: "3.7"

services:
  unleash-db:
    image: postgres:10-alpine
    expose:
      - "5432"
    environment:
      POSTGRES_USER: unleash
      POSTGRES_DB: unleash
      POSTGRES_PASSWORD: passw0rd

  unleash:
    build: ./unleash
    environment:
      DATABASE_URL: postgres://unleash:passw0rd@unleash-db:5432/unleash
      SHARED_SECRET: abc123
      GOOGLE_CALLBACK_URL: http://localhost:4242/api/auth/callback
      GOOGLE_CLIENT_ID: ${UNLEASH_GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${UNLEASH_GOOGLE_CLIENT_SECRET}
      WHITELISTED_EMAIL_DOMAINS: ${UNLEASH_WHITELISTED_EMAIL_DOMAINS}
    ports:
      - "4242:4242" # expose on localhost:4242

  server:
    build: ./server
    command: npm run start
    environment:
      PORT: 3001
      UNLEASH_API_BASE: http://unleash:4242/api # unleash API address
      UNLEASH_REFRESH_INTERVAL: 5000 # poll every 5 seconds
      UNLEASH_SHARED_SECRET: abc123
      APP_NAME: foo # identify our app with unleash
      INSTANCE_ID: bar # identify this instance with unleash
    volumes:
      - ./server:/usr/app/ # mount ./server at /usr/app in the container
      - /usr/app/node_modules # cache node_modules in a volume
    ports:
      - "3001:3001" # expose on localhost:3001
