version: "3.7"

services:
  unleash-db:
    image: postgres:10-alpine
    expose:
      - "5432"
    environment:
      POSTGRES_USER: unleash
      POSTGRES_DB: unleash
      POSTGRES_PASSWORD: passw0rd

  unleash:
    image: unleashorg/unleash-server
    environment:
      DATABASE_URL: postgres://unleash:passw0rd@unleash-db:5432/unleash
    ports:
      - "4242:4242" # expose on localhost:4242

  server:
    build: ./server
    command: npm run start
    volumes:
      - ./server:/usr/app/ # mount ./server at /usr/app in the container
      - /usr/app/node_modules # cache node_modules in a volume
    ports:
      - "3000:3000" # expose on localhost:3000

